name: 3DS build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile 3DS build
        run: |
          make

      - name: Move into folder
        run: |
          mkdir -p artifact/3ds/ddnet
          cp ddnet-3ds.3dsx artifact/3ds/
          cp -r data/* artifact/3ds/ddnet/

      - name: Upload .3dsx artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3DS ROM
          path: ./artifact

      - name: Upload .elf artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddnet-3ds.elf
          path: ./ddnet-3ds.elf
